#!/bin/bash
NASPath=$(cat /opt/eznas/mountrute.txt)
ObjectivePath=$(cat /opt/eznas/localroute.txt)

if [[ $# -eq 0 ]]; then
    echo "comando incorrecto, pruebe usar eznas -h para ver las opciones disponibles"
    exit 1
fi
case $1 in
    '-s')
        /opt/eznas/setup.sh
    ;;
    '-p')
         if [[ $# -eq 3 ]]; then
        /opt/eznas/credentials.sh $2 $3
        else
        /opt/eznas/credentials.sh
        fi
    ;;
    '-l')
        if [[ $# -eq 2 ]]; then
            /opt/eznas/localroute.sh $2
        else
            /opt/eznas/localroute.sh
        fi
    ;;
    '-c')
        /opt/eznas/01Respaldo.sh
    ;;

    '-h')
        echo "Opción no disponible"
    ;;
    '-g')
        nano /opt/eznas/TOCP.txt
    ;;
    *)
        echo "comando incorrecto, pruebe usar eznas -h para ver las opciones disponibles"
        exit 1
    ;;
esac
exit $?
